'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace cl.agroinsumos.wssap_test
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="srvOrdenVentaSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class srvOrdenVenta
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RegistrarBorradorVentaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarOrdenVentaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarOrdenVentaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegistrarOrdenVentaEnBorradorVentaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SistemaVentasWeb.My.MySettings.Default.SistemaVentasWeb_cl_agroinsumos_wssap_test_srvOrdenVenta
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RegistrarBorradorVentaCompleted As RegistrarBorradorVentaCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarOrdenVentaCompleted As RegistrarOrdenVentaCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarOrdenVentaCompleted As CancelarOrdenVentaCompletedEventHandler
        
        '''<remarks/>
        Public Event RegistrarOrdenVentaEnBorradorVentaCompleted As RegistrarOrdenVentaEnBorradorVentaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarBorradorVenta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarBorradorVenta( _
                    ByVal intUsuario As Integer,  _
                    ByVal strTipoVenta As String,  _
                    ByVal strCliente As String,  _
                    ByVal strMonedaPago As String,  _
                    ByVal strOrdenCompra As String,  _
                    ByVal intVendedor As Integer,  _
                    ByVal intOperador As Integer,  _
                    ByVal strFechaOrdenVenta As String,  _
                    ByVal strFechaEntrega As String,  _
                    ByVal intSerie As Integer,  _
                    ByVal intTipoDespacho As Integer,  _
                    ByVal strNotaPedido As String,  _
                    ByVal intCodigoPlazoVenta As Integer,  _
                    ByVal strFechaVencimiento As String,  _
                    ByVal intCodigoPlazoCompra As Integer,  _
                    ByVal strDireccionFactura As String,  _
                    ByVal strDireccionDespacho As String,  _
                    ByVal strComentario1 As String,  _
                    ByVal strComentario2 As String,  _
                    ByVal strComentario3 As String,  _
                    ByVal intMotivo As Integer,  _
                    ByVal strEmision As String,  _
                    ByVal strGuiaDespacho As String,  _
                    ByVal strPedido As String) As String
            Dim results() As Object = Me.Invoke("RegistrarBorradorVenta", New Object() {intUsuario, strTipoVenta, strCliente, strMonedaPago, strOrdenCompra, intVendedor, intOperador, strFechaOrdenVenta, strFechaEntrega, intSerie, intTipoDespacho, strNotaPedido, intCodigoPlazoVenta, strFechaVencimiento, intCodigoPlazoCompra, strDireccionFactura, strDireccionDespacho, strComentario1, strComentario2, strComentario3, intMotivo, strEmision, strGuiaDespacho, strPedido})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarBorradorVentaAsync( _
                    ByVal intUsuario As Integer,  _
                    ByVal strTipoVenta As String,  _
                    ByVal strCliente As String,  _
                    ByVal strMonedaPago As String,  _
                    ByVal strOrdenCompra As String,  _
                    ByVal intVendedor As Integer,  _
                    ByVal intOperador As Integer,  _
                    ByVal strFechaOrdenVenta As String,  _
                    ByVal strFechaEntrega As String,  _
                    ByVal intSerie As Integer,  _
                    ByVal intTipoDespacho As Integer,  _
                    ByVal strNotaPedido As String,  _
                    ByVal intCodigoPlazoVenta As Integer,  _
                    ByVal strFechaVencimiento As String,  _
                    ByVal intCodigoPlazoCompra As Integer,  _
                    ByVal strDireccionFactura As String,  _
                    ByVal strDireccionDespacho As String,  _
                    ByVal strComentario1 As String,  _
                    ByVal strComentario2 As String,  _
                    ByVal strComentario3 As String,  _
                    ByVal intMotivo As Integer,  _
                    ByVal strEmision As String,  _
                    ByVal strGuiaDespacho As String,  _
                    ByVal strPedido As String)
            Me.RegistrarBorradorVentaAsync(intUsuario, strTipoVenta, strCliente, strMonedaPago, strOrdenCompra, intVendedor, intOperador, strFechaOrdenVenta, strFechaEntrega, intSerie, intTipoDespacho, strNotaPedido, intCodigoPlazoVenta, strFechaVencimiento, intCodigoPlazoCompra, strDireccionFactura, strDireccionDespacho, strComentario1, strComentario2, strComentario3, intMotivo, strEmision, strGuiaDespacho, strPedido, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarBorradorVentaAsync( _
                    ByVal intUsuario As Integer,  _
                    ByVal strTipoVenta As String,  _
                    ByVal strCliente As String,  _
                    ByVal strMonedaPago As String,  _
                    ByVal strOrdenCompra As String,  _
                    ByVal intVendedor As Integer,  _
                    ByVal intOperador As Integer,  _
                    ByVal strFechaOrdenVenta As String,  _
                    ByVal strFechaEntrega As String,  _
                    ByVal intSerie As Integer,  _
                    ByVal intTipoDespacho As Integer,  _
                    ByVal strNotaPedido As String,  _
                    ByVal intCodigoPlazoVenta As Integer,  _
                    ByVal strFechaVencimiento As String,  _
                    ByVal intCodigoPlazoCompra As Integer,  _
                    ByVal strDireccionFactura As String,  _
                    ByVal strDireccionDespacho As String,  _
                    ByVal strComentario1 As String,  _
                    ByVal strComentario2 As String,  _
                    ByVal strComentario3 As String,  _
                    ByVal intMotivo As Integer,  _
                    ByVal strEmision As String,  _
                    ByVal strGuiaDespacho As String,  _
                    ByVal strPedido As String,  _
                    ByVal userState As Object)
            If (Me.RegistrarBorradorVentaOperationCompleted Is Nothing) Then
                Me.RegistrarBorradorVentaOperationCompleted = AddressOf Me.OnRegistrarBorradorVentaOperationCompleted
            End If
            Me.InvokeAsync("RegistrarBorradorVenta", New Object() {intUsuario, strTipoVenta, strCliente, strMonedaPago, strOrdenCompra, intVendedor, intOperador, strFechaOrdenVenta, strFechaEntrega, intSerie, intTipoDespacho, strNotaPedido, intCodigoPlazoVenta, strFechaVencimiento, intCodigoPlazoCompra, strDireccionFactura, strDireccionDespacho, strComentario1, strComentario2, strComentario3, intMotivo, strEmision, strGuiaDespacho, strPedido}, Me.RegistrarBorradorVentaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarBorradorVentaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarBorradorVentaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarBorradorVentaCompleted(Me, New RegistrarBorradorVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarOrdenVenta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarOrdenVenta( _
                    ByVal intUsuario As Integer,  _
                    ByVal strTipoVenta As String,  _
                    ByVal strCliente As String,  _
                    ByVal strMonedaPago As String,  _
                    ByVal strOrdenCompra As String,  _
                    ByVal intVendedor As Integer,  _
                    ByVal intOperador As Integer,  _
                    ByVal strFechaOrdenVenta As String,  _
                    ByVal strFechaEntrega As String,  _
                    ByVal intSerie As Integer,  _
                    ByVal intTipoDespacho As Integer,  _
                    ByVal strNotaPedido As String,  _
                    ByVal intCodigoPlazoVenta As Integer,  _
                    ByVal strFechaVencimiento As String,  _
                    ByVal intCodigoPlazoCompra As Integer,  _
                    ByVal strDireccionFactura As String,  _
                    ByVal strDireccionDespacho As String,  _
                    ByVal strComentario1 As String,  _
                    ByVal strComentario2 As String,  _
                    ByVal strComentario3 As String,  _
                    ByVal intMotivo As Integer,  _
                    ByVal strEmision As String,  _
                    ByVal strGuiaDespacho As String,  _
                    ByVal strPedido As String) As String
            Dim results() As Object = Me.Invoke("RegistrarOrdenVenta", New Object() {intUsuario, strTipoVenta, strCliente, strMonedaPago, strOrdenCompra, intVendedor, intOperador, strFechaOrdenVenta, strFechaEntrega, intSerie, intTipoDespacho, strNotaPedido, intCodigoPlazoVenta, strFechaVencimiento, intCodigoPlazoCompra, strDireccionFactura, strDireccionDespacho, strComentario1, strComentario2, strComentario3, intMotivo, strEmision, strGuiaDespacho, strPedido})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarOrdenVentaAsync( _
                    ByVal intUsuario As Integer,  _
                    ByVal strTipoVenta As String,  _
                    ByVal strCliente As String,  _
                    ByVal strMonedaPago As String,  _
                    ByVal strOrdenCompra As String,  _
                    ByVal intVendedor As Integer,  _
                    ByVal intOperador As Integer,  _
                    ByVal strFechaOrdenVenta As String,  _
                    ByVal strFechaEntrega As String,  _
                    ByVal intSerie As Integer,  _
                    ByVal intTipoDespacho As Integer,  _
                    ByVal strNotaPedido As String,  _
                    ByVal intCodigoPlazoVenta As Integer,  _
                    ByVal strFechaVencimiento As String,  _
                    ByVal intCodigoPlazoCompra As Integer,  _
                    ByVal strDireccionFactura As String,  _
                    ByVal strDireccionDespacho As String,  _
                    ByVal strComentario1 As String,  _
                    ByVal strComentario2 As String,  _
                    ByVal strComentario3 As String,  _
                    ByVal intMotivo As Integer,  _
                    ByVal strEmision As String,  _
                    ByVal strGuiaDespacho As String,  _
                    ByVal strPedido As String)
            Me.RegistrarOrdenVentaAsync(intUsuario, strTipoVenta, strCliente, strMonedaPago, strOrdenCompra, intVendedor, intOperador, strFechaOrdenVenta, strFechaEntrega, intSerie, intTipoDespacho, strNotaPedido, intCodigoPlazoVenta, strFechaVencimiento, intCodigoPlazoCompra, strDireccionFactura, strDireccionDespacho, strComentario1, strComentario2, strComentario3, intMotivo, strEmision, strGuiaDespacho, strPedido, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarOrdenVentaAsync( _
                    ByVal intUsuario As Integer,  _
                    ByVal strTipoVenta As String,  _
                    ByVal strCliente As String,  _
                    ByVal strMonedaPago As String,  _
                    ByVal strOrdenCompra As String,  _
                    ByVal intVendedor As Integer,  _
                    ByVal intOperador As Integer,  _
                    ByVal strFechaOrdenVenta As String,  _
                    ByVal strFechaEntrega As String,  _
                    ByVal intSerie As Integer,  _
                    ByVal intTipoDespacho As Integer,  _
                    ByVal strNotaPedido As String,  _
                    ByVal intCodigoPlazoVenta As Integer,  _
                    ByVal strFechaVencimiento As String,  _
                    ByVal intCodigoPlazoCompra As Integer,  _
                    ByVal strDireccionFactura As String,  _
                    ByVal strDireccionDespacho As String,  _
                    ByVal strComentario1 As String,  _
                    ByVal strComentario2 As String,  _
                    ByVal strComentario3 As String,  _
                    ByVal intMotivo As Integer,  _
                    ByVal strEmision As String,  _
                    ByVal strGuiaDespacho As String,  _
                    ByVal strPedido As String,  _
                    ByVal userState As Object)
            If (Me.RegistrarOrdenVentaOperationCompleted Is Nothing) Then
                Me.RegistrarOrdenVentaOperationCompleted = AddressOf Me.OnRegistrarOrdenVentaOperationCompleted
            End If
            Me.InvokeAsync("RegistrarOrdenVenta", New Object() {intUsuario, strTipoVenta, strCliente, strMonedaPago, strOrdenCompra, intVendedor, intOperador, strFechaOrdenVenta, strFechaEntrega, intSerie, intTipoDespacho, strNotaPedido, intCodigoPlazoVenta, strFechaVencimiento, intCodigoPlazoCompra, strDireccionFactura, strDireccionDespacho, strComentario1, strComentario2, strComentario3, intMotivo, strEmision, strGuiaDespacho, strPedido}, Me.RegistrarOrdenVentaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarOrdenVentaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarOrdenVentaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarOrdenVentaCompleted(Me, New RegistrarOrdenVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelarOrdenVenta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelarOrdenVenta(ByVal intDocCodigo As String, ByVal intUsuario As String) As String
            Dim results() As Object = Me.Invoke("CancelarOrdenVenta", New Object() {intDocCodigo, intUsuario})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarOrdenVentaAsync(ByVal intDocCodigo As String, ByVal intUsuario As String)
            Me.CancelarOrdenVentaAsync(intDocCodigo, intUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarOrdenVentaAsync(ByVal intDocCodigo As String, ByVal intUsuario As String, ByVal userState As Object)
            If (Me.CancelarOrdenVentaOperationCompleted Is Nothing) Then
                Me.CancelarOrdenVentaOperationCompleted = AddressOf Me.OnCancelarOrdenVentaOperationCompleted
            End If
            Me.InvokeAsync("CancelarOrdenVenta", New Object() {intDocCodigo, intUsuario}, Me.CancelarOrdenVentaOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarOrdenVentaOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarOrdenVentaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarOrdenVentaCompleted(Me, New CancelarOrdenVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarOrdenVentaEnBorradorVenta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegistrarOrdenVentaEnBorradorVenta(ByVal intUsuario As Integer, ByVal intDocEntry As Integer) As String
            Dim results() As Object = Me.Invoke("RegistrarOrdenVentaEnBorradorVenta", New Object() {intUsuario, intDocEntry})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegistrarOrdenVentaEnBorradorVentaAsync(ByVal intUsuario As Integer, ByVal intDocEntry As Integer)
            Me.RegistrarOrdenVentaEnBorradorVentaAsync(intUsuario, intDocEntry, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarOrdenVentaEnBorradorVentaAsync(ByVal intUsuario As Integer, ByVal intDocEntry As Integer, ByVal userState As Object)
            If (Me.RegistrarOrdenVentaEnBorradorVentaOperationCompleted Is Nothing) Then
                Me.RegistrarOrdenVentaEnBorradorVentaOperationCompleted = AddressOf Me.OnRegistrarOrdenVentaEnBorradorVentaOperationCompleted
            End If
            Me.InvokeAsync("RegistrarOrdenVentaEnBorradorVenta", New Object() {intUsuario, intDocEntry}, Me.RegistrarOrdenVentaEnBorradorVentaOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarOrdenVentaEnBorradorVentaOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarOrdenVentaEnBorradorVentaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarOrdenVentaEnBorradorVentaCompleted(Me, New RegistrarOrdenVentaEnBorradorVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub RegistrarBorradorVentaCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarBorradorVentaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarBorradorVentaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub RegistrarOrdenVentaCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarOrdenVentaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarOrdenVentaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub CancelarOrdenVentaCompletedEventHandler(ByVal sender As Object, ByVal e As CancelarOrdenVentaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarOrdenVentaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub RegistrarOrdenVentaEnBorradorVentaCompletedEventHandler(ByVal sender As Object, ByVal e As RegistrarOrdenVentaEnBorradorVentaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegistrarOrdenVentaEnBorradorVentaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
