'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace PDFE
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="VisualizacionServiceSoap11Binding", [Namespace]:="http://visualizaciondoc.webservices.dte.azurian.com")>  _
    Partial Public Class VisualizacionService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private visualizacionPDFOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SistemaVentasWeb.My.MySettings.Default.SistemaVentasWeb_com_azurian_cloudtattersallqa_VisualizacionService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event visualizacionPDFCompleted As visualizacionPDFCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:visualizacionPDF", RequestNamespace:="http://visualizaciondoc.webservices.dte.azurian.com", ResponseNamespace:="http://visualizaciondoc.webservices.dte.azurian.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function visualizacionPDF(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As VisualizacionRequest) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> VisualizacionResponse
            Dim results() As Object = Me.Invoke("visualizacionPDF", New Object() {request})
            Return CType(results(0),VisualizacionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub visualizacionPDFAsync(ByVal request As VisualizacionRequest)
            Me.visualizacionPDFAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub visualizacionPDFAsync(ByVal request As VisualizacionRequest, ByVal userState As Object)
            If (Me.visualizacionPDFOperationCompleted Is Nothing) Then
                Me.visualizacionPDFOperationCompleted = AddressOf Me.OnvisualizacionPDFOperationCompleted
            End If
            Me.InvokeAsync("visualizacionPDF", New Object() {request}, Me.visualizacionPDFOperationCompleted, userState)
        End Sub
        
        Private Sub OnvisualizacionPDFOperationCompleted(ByVal arg As Object)
            If (Not (Me.visualizacionPDFCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent visualizacionPDFCompleted(Me, New visualizacionPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://visualizaciondoc.webservices.dte.azurian.com/xsd")>  _
    Partial Public Class VisualizacionRequest
        
        Private apiKeyField As String
        
        Private numeroFolioField As Long
        
        Private numeroFolioFieldSpecified As Boolean
        
        Private resolucionSiiField As Integer
        
        Private resolucionSiiFieldSpecified As Boolean
        
        Private rutEmpresaField As Integer
        
        Private rutEmpresaFieldSpecified As Boolean
        
        Private tipoDocumentoField As Integer
        
        Private tipoDocumentoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property apiKey() As String
            Get
                Return Me.apiKeyField
            End Get
            Set
                Me.apiKeyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property numeroFolio() As Long
            Get
                Return Me.numeroFolioField
            End Get
            Set
                Me.numeroFolioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroFolioSpecified() As Boolean
            Get
                Return Me.numeroFolioFieldSpecified
            End Get
            Set
                Me.numeroFolioFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resolucionSii() As Integer
            Get
                Return Me.resolucionSiiField
            End Get
            Set
                Me.resolucionSiiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property resolucionSiiSpecified() As Boolean
            Get
                Return Me.resolucionSiiFieldSpecified
            End Get
            Set
                Me.resolucionSiiFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rutEmpresa() As Integer
            Get
                Return Me.rutEmpresaField
            End Get
            Set
                Me.rutEmpresaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property rutEmpresaSpecified() As Boolean
            Get
                Return Me.rutEmpresaFieldSpecified
            End Get
            Set
                Me.rutEmpresaFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipoDocumento() As Integer
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property tipoDocumentoSpecified() As Boolean
            Get
                Return Me.tipoDocumentoFieldSpecified
            End Get
            Set
                Me.tipoDocumentoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://visualizaciondoc.webservices.dte.azurian.com/xsd")>  _
    Partial Public Class VisualizacionResponse
        
        Private codigoRespuestaField As String
        
        Private pdf64DocumentoField As String
        
        Private respuestaField As String
        
        Private urlDocumentoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property codigoRespuesta() As String
            Get
                Return Me.codigoRespuestaField
            End Get
            Set
                Me.codigoRespuestaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property pdf64Documento() As String
            Get
                Return Me.pdf64DocumentoField
            End Get
            Set
                Me.pdf64DocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property respuesta() As String
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property urlDocumento() As String
            Get
                Return Me.urlDocumentoField
            End Get
            Set
                Me.urlDocumentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub visualizacionPDFCompletedEventHandler(ByVal sender As Object, ByVal e As visualizacionPDFCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class visualizacionPDFCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As VisualizacionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),VisualizacionResponse)
            End Get
        End Property
    End Class
End Namespace
