'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rscServicioWeb
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebServices.rscServicioWeb", GetType(rscServicioWeb).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a TAI_PRD.
        '''</summary>
        Friend Shared ReadOnly Property DataPRD() As String
            Get
                Return ResourceManager.GetString("DataPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a TAI_PRD_20241109.
        '''</summary>
        Friend Shared ReadOnly Property DataTST() As String
            Get
                Return ResourceManager.GetString("DataTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SaP.5.2016.
        '''</summary>
        Friend Shared ReadOnly Property PasswordPRD() As String
            Get
                Return ResourceManager.GetString("PasswordPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SaP.5.2016.
        '''</summary>
        Friend Shared ReadOnly Property PasswordTST() As String
            Get
                Return ResourceManager.GetString("PasswordTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SQLCORP01:30000.
        '''</summary>
        Friend Shared ReadOnly Property ServerLICENCIAS() As String
            Get
                Return ResourceManager.GetString("ServerLICENCIAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SQLCORP01\SQLCORP01.
        '''</summary>
        Friend Shared ReadOnly Property ServerPRD() As String
            Get
                Return ResourceManager.GetString("ServerPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SQLCORP01\SQLCORP01.
        '''</summary>
        Friend Shared ReadOnly Property ServerTST() As String
            Get
                Return ResourceManager.GetString("ServerTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a sapsa.
        '''</summary>
        Friend Shared ReadOnly Property UserPRD() As String
            Get
                Return ResourceManager.GetString("UserPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a sapsa.
        '''</summary>
        Friend Shared ReadOnly Property UserTST() As String
            Get
                Return ResourceManager.GetString("UserTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a T.
        '''</summary>
        Friend Shared ReadOnly Property zModalidad() As String
            Get
                Return ResourceManager.GetString("zModalidad", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
