'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rscSistemaVentasWeb
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SistemaVentasWeb.rscSistemaVentasWeb", GetType(rscSistemaVentasWeb).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a d45d3751fe8c47539ec501cd8749a15705ceece5d8d5696f2f20565ecf88.
        '''</summary>
        Friend Shared ReadOnly Property ApiKeyPRD() As String
            Get
                Return ResourceManager.GetString("ApiKeyPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0709eade119adb38465245bffa9b9e8907a947e72f64a7d54c368364c388.
        '''</summary>
        Friend Shared ReadOnly Property ApyKeyTST() As String
            Get
                Return ResourceManager.GetString("ApyKeyTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ecanales@tattersall.cl.
        '''</summary>
        Friend Shared ReadOnly Property CorreoReceptorPRD() As String
            Get
                Return ResourceManager.GetString("CorreoReceptorPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a asegovia@tattersall.cl.
        '''</summary>
        Friend Shared ReadOnly Property CorreoReceptorTST() As String
            Get
                Return ResourceManager.GetString("CorreoReceptorTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a TAI_PRD.
        '''</summary>
        Friend Shared ReadOnly Property DataPRD() As String
            Get
                Return ResourceManager.GetString("DataPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a TEST_TAI_13042026.
        '''</summary>
        Friend Shared ReadOnly Property DataTST() As String
            Get
                Return ResourceManager.GetString("DataTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SaP.5.2016.
        '''</summary>
        Friend Shared ReadOnly Property PasswordPRD() As String
            Get
                Return ResourceManager.GetString("PasswordPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SaP.5.2016.
        '''</summary>
        Friend Shared ReadOnly Property PasswordTST() As String
            Get
                Return ResourceManager.GetString("PasswordTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SQLCORP01:30000.
        '''</summary>
        Friend Shared ReadOnly Property ServerLICENCIAS() As String
            Get
                Return ResourceManager.GetString("ServerLICENCIAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SQLCORP01\SQLCORP01.
        '''</summary>
        Friend Shared ReadOnly Property ServerPRD() As String
            Get
                Return ResourceManager.GetString("ServerPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SQLCORP01\SQLCORP01.
        '''</summary>
        Friend Shared ReadOnly Property ServerTST() As String
            Get
                Return ResourceManager.GetString("ServerTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a http://ventas.agroinsumos.cl.
        '''</summary>
        Friend Shared ReadOnly Property ServerWebPRD() As String
            Get
                Return ResourceManager.GetString("ServerWebPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a http://ventas_test.agroinsumos.cl.
        '''</summary>
        Friend Shared ReadOnly Property ServerWebTST() As String
            Get
                Return ResourceManager.GetString("ServerWebTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a http://sqldte1:8080/DTEPlus/VisualizarDocumento/?resolucion=%r&amp;folio=%f&amp;rut=96775400&amp;tipo=%t.
        '''</summary>
        Friend Shared ReadOnly Property URLFacturacionPRD() As String
            Get
                Return ResourceManager.GetString("URLFacturacionPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a http://appdte3:8080/DTEPlus/VisualizarDocumento/?resolucion=%r&amp;folio=%f&amp;rut=96775400&amp;tipo=%t.
        '''</summary>
        Friend Shared ReadOnly Property URLFacturacionTST() As String
            Get
                Return ResourceManager.GetString("URLFacturacionTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 79.
        '''</summary>
        Friend Shared ReadOnly Property URLResolucionPRD() As String
            Get
                Return ResourceManager.GetString("URLResolucionPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 0.
        '''</summary>
        Friend Shared ReadOnly Property URLResolucionTST() As String
            Get
                Return ResourceManager.GetString("URLResolucionTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a sapsa.
        '''</summary>
        Friend Shared ReadOnly Property UserPRD() As String
            Get
                Return ResourceManager.GetString("UserPRD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a sapsa.
        '''</summary>
        Friend Shared ReadOnly Property UserTST() As String
            Get
                Return ResourceManager.GetString("UserTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Creditos.
        '''</summary>
        Friend Shared ReadOnly Property wAutorizacionCredito() As String
            Get
                Return ResourceManager.GetString("wAutorizacionCredito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Deuda Vencida.
        '''</summary>
        Friend Shared ReadOnly Property wAutorizacionDeuda() As String
            Get
                Return ResourceManager.GetString("wAutorizacionDeuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Protestos.
        '''</summary>
        Friend Shared ReadOnly Property wAutorizacionProtesto() As String
            Get
                Return ResourceManager.GetString("wAutorizacionProtesto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a A.
        '''</summary>
        Friend Shared ReadOnly Property wBorradorEstadoAutorizado() As String
            Get
                Return ResourceManager.GetString("wBorradorEstadoAutorizado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a N.
        '''</summary>
        Friend Shared ReadOnly Property wBorradorEstadoAutorizadoNoCreado() As String
            Get
                Return ResourceManager.GetString("wBorradorEstadoAutorizadoNoCreado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a P.
        '''</summary>
        Friend Shared ReadOnly Property wBorradorEstadoPendiente() As String
            Get
                Return ResourceManager.GetString("wBorradorEstadoPendiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a R.
        '''</summary>
        Friend Shared ReadOnly Property wBorradorEstadoRechazado() As String
            Get
                Return ResourceManager.GetString("wBorradorEstadoRechazado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a T.
        '''</summary>
        Friend Shared ReadOnly Property wBorradorEstadoTerminado() As String
            Get
                Return ResourceManager.GetString("wBorradorEstadoTerminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ttai@tattersall.cl.
        '''</summary>
        Friend Shared ReadOnly Property wCorreoEmisor() As String
            Get
                Return ResourceManager.GetString("wCorreoEmisor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 10.
        '''</summary>
        Friend Shared ReadOnly Property wWaitCicloFolio() As String
            Get
                Return ResourceManager.GetString("wWaitCicloFolio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 5.
        '''</summary>
        Friend Shared ReadOnly Property wWaitForFolio() As String
            Get
                Return ResourceManager.GetString("wWaitForFolio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a T.
        '''</summary>
        Friend Shared ReadOnly Property zModalidad() As String
            Get
                Return ResourceManager.GetString("zModalidad", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
